function mouseButtonEventHandler(button, clicks, state, x, y)
	print("mouseButtonEvent")
	print("    button: " .. button)
	print("    clicks: " .. clicks)
	print("    state: " .. state)
	print("    x: " .. x)
	print("    y: " .. y)
	print()
end
addEventHandler("mouseButtonEvent", mouseButtonEventHandler)

function mouseMotionEventHandler(state, x, y, xrel, yrel)
	print("mouseMotionEvent")
	print("    state: " .. state)
	print("    x: " .. x)
	print("    y: " .. y)
	print("    xrel: " .. xrel)
	print("    yrel: " .. yrel)
	print()
end
addEventHandler("mouseMotionEvent", mouseMotionEventHandler)